name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu/server/forest-vendor-integration

            git fetch origin main
            git reset --hard origin/main

            docker build \
              -f dockerfile \
              -t forest-vendor-integration .

            docker rm -f forest-vendor-integration || true

            docker run -d \
              --name forest-vendor-integration \
              --restart unless-stopped \
              -p 127.0.0.1:18010:18010 \
              forest-vendor-integration